version: '3.1'
services:
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: myuser
      POSTGRES_DB: planet9
    ports:
      - 5432:5432
    volumes:
      - "pgdataLatest:/var/lib/postgresql/data"
      - ./db-init:/docker-entrypoint-initdb.d
  dbgui:
    image: adminer
    restart: always
    ports:
      - 3000:8080
  planet9:
    image: neptunesoftware/planet9:v2.5.1
    environment:
      NODE_ENV: development
      DB_URI_POSTGRES: postgress://myuser:mypassword@db:5432/planet9
      DB_TYPE: postgresql
    volumes:
      - "./volume:/home/planet9/ext-dir"
    ports:
      - 8080:8080
volumes:
  pgdataLatest: